export PROVER_MODE=dev
export NOTARY_URL=http://localhost:7779
export SINK_STELLAR_SECRET=SCH67D4MVGQCIE3NOLND5TY25EN6NVAZAASYD5CQKEC3UY3REMJJMCCO
export SINK_STELLAR_RPC=https://soroban-testnet.stellar.org:443