[package]
name = "prover"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "2"
url = "2.2.2"
actix-web = "4.3.1"
tokio-util = "0.7"
serde = { version = "1.0.159", features = ["derive"] }
futures-util = "0.3.30"
hyper = { version = "0.14", features = ["client", "http1"] }
tlsn-core = { git = "https://github.com/tlsnotary/tlsn", rev = "6152883" }
tlsn-prover = { git = "https://github.com/tlsnotary/tlsn", rev = "6152883" }
time = { version = "0.3", features = ["wasm-bindgen"] }
tokio = { version = "1", features = ["full"] }
web-time = "0.2"
futures = "0.3"
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-rustls = { version = "0.24.1" }
rustls-pemfile = { version = "1.0.2" }
rustls = { version = "0.21" }
prost = "0.12.3"
zmq = "0.10.0"
anyhow = "1.0.79"
sha2 = "0.10.8"


[build-dependencies]
prost-build = "0.12.3"
protobuf-zmq-rust-generator = "0.1.1"
