name: Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      # temporary
      - feature/push-image-action

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build --platform linux/amd64 -t logstore-node -f ./Dockerfile --cache-from type=gha,scope=usherlabs/logstore-node --cache-to type=gha,mode=max,scope=usherlabs/logstore-node .

      - name: Tag image
        run: |
          # if master, tag as latest
          tag=latest
          # if not master, tag as branch name
          if [ $GITHUB_REF != 'refs/heads/master' ]; then
              tag=$(echo $GITHUB_REF | sed 's/refs\/heads\///' | sed 's/\//-/')
          fi
          image_name=${{ env.REGISTRY }}/$GITHUB_REPOSITORY/logstore-node:$tag
          docker tag logstore-node $image_name
          echo "Tagged image as $image_name"
          # save for next step
          echo "image_name=$image_name" >> $GITHUB_ENV

      - name: Push image to GitHub Container Registry
        if: ${{ !env.ACT }} # skip during local actions testing
        run: |
          docker push $image_name
