name: Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      # temporary
      - feature/push-image-action

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build --platform linux/amd64 -t logstore-node -f ./Dockerfile --cache-from type=gha,scope=usherlabs/logstore-node --cache-to type=gha,mode=max,scope=usherlabs/logstore-node .

      - name: Tag image
        run: |
          # if master, tag as latest
          tag=latest
          # if not master, tag as branch name
          if [ $GITHUB_REF != 'refs/heads/master' ]; then
              tag=$(echo $GITHUB_REF | sed 's/refs\/heads\///' | sed 's/\//-/')
          fi
          docker tag logstore-node logstore-node:$tag
          echo "Tagged image as logstore-node:$tag"

      - name: Push image to GitHub Container Registry
        if: ${{ !env.ACT }} # skip during local actions testing
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/$GITHUB_REPOSITORY/logstore-node:$tag


